on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: run pipeline
        run: |
          git clone https://github.com/Mist3rBru/cineapp.git
          cd cineapp
          npm install
          npm run build
          cd dist
          git init
          git config user.name 'Bruno Rocha'
          git config user.email 'brunorocha2674@gmail.com'
          git checkout -b master:gh-pages
          git add .
          git commit -m 'deploy'
          git push -f https://github.com/Mist3rBru/cineapp.git master:gh-pages
