# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: build app
        run: sh ./deploy.sh
        shell: pwsh
