on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: run pipeline
        run: |
          git clone https://github.com/Mist3rBru/cineapp.git
          cd cineapp
          npm install
          npm run build
          cd dist
          git init
          git remote add origin https://github.com/Mist3rBru/cineapp.git
          git config user.name Mist3rBru
          git config user.email brunorocha2674@gmail.com
          git checkout -b gh-page
          git add .
          git commit -m 'deploy'
          git push origin gh-page
