on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: build app
        run: |
          npm install
          npm run build
          cd dist
          git init
          git checkout -b main
          git add .
          git commit -m 'deploy'
          git push -f https://github.com/Mist3rBru/cineapp.git main:gh-pages
