on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: build app
        run: |
          git clone https://github.com/Mist3rBru/cineapp.git
          cd cineapp
          npm install
          npm run build
          cd dist
          git init
          git config user.name 'bruno_bot'
          git config user.email 'mister.rocha1234@gmail.com'
          git add .
          git commit -m 'deploy'
          git push origin master:gh-pages
